#!/usr/bin/python3
n = int(input())
for i in range(n):    
    a,b=map(int,input().split())
    if(a%2==0):
        d = (b-a-1)%4
        if(d>1):
            print('Even')
        else:
            print('Odd')
    else:
        d = (b-a)%4
        if(d>1):
            print('Even')
        else:
            print('Odd')
