#!/usr/bin/python3
i =  int(input())
result = []
while i > 0:    
    a,b=map(int,input().split())
    XOR = a
    while b > a:
        XOR,a = XOR^(a+1),a+1
    if(XOR%2 == 0):
        result.append('Even')
    else:
        result.append('Odd')
    i = i - 1
    
    
for m in range(len(result)):
    print(result[m])
