#!/usr/bin/python3
import requests
import time
import json

# 通过分析XHR,找到query这个链接
# 然后把query string parameters的参数copy到params中
# 分析参数timestamp是由实时时间转成13位数字的，以及pageIndex是翻页页数，最后访问到json文本

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36',
}

url_r = 'https://careers.tencent.com/tencentcareer/api/post/Query'

count = 0
for page in range(661):
    # 设置参数中的时间戳
    timestamp = round(time.time(), 3) * 1000
    # 页数参数
    params = {
        'timestamp': timestamp,
        'countryId': '',
        'cityId': '',
        'bgIds': '',
        'productId': '',
        'categoryId': '',
        'parentCategoryId': '',
        'attrId': '',
        'keyword': '',
        'pageIndex': str(page + 1),
        'pageSize': ' 10',
        'language': ' zh-cn',
        'area': ' cn',
    }

    response = requests.get(url_r, headers=headers, params=params)
    text = response.text
    jason_text = json.loads(text)
    # 分析jason文件，找到目标数据
    get_data = jason_text['Data']['Posts']

    # 迭代输出列表中的目标数据
    for item in get_data:
        count += 1
        RecruitPostName = item['RecruitPostName']  # 职位名称
        Responsibility = item['Responsibility']  # 职位描述
        LastUpdateTime = item['LastUpdateTime']  # 最近更新时间
        BGName = item['BGName']  # 部门名称
        CountryName = item['CountryName']  # 国家
        LocationName = item['LocationName']  # 城市
        print('岗位'+ str(count) +'：')
        print('岗位名称：' + RecruitPostName + '\n' +
              '岗位描述：' + Responsibility.strip() + '\n' +
              '国家，城市：' + CountryName + ',' + LocationName + '\n'
              '最近更新时间：' + LastUpdateTime + '\n' +
              '部门名称：' + BGName)
